function SectionLabel({ number, label }: { number: string; label: string }) {
  return (
    <div className="flex items-center gap-3 mb-5">
      <span className="font-mono text-[11px] font-bold text-[#94A3B8] tracking-widest">{number}</span>
      <span className="h-px flex-1 bg-[#E2E8F0] max-w-[40px]" />
      <span className="font-mono text-[11px] font-semibold text-[#94A3B8] uppercase tracking-widest">{label}</span>
    </div>
  );
}

const tables = [
  { name: "patients", desc: "Demographics: age, sex, civil status, branch, contact profile" },
  { name: "orders", desc: "Transactions: totals, discounts, payment status, branch, partner" },
  { name: "order_items", desc: "Line items: product and service names, discounts, statuses" },
  { name: "patient_services", desc: "Service execution: status, timestamps, workflow progression" },
  { name: "patient_service_results", desc: "Lab values and reference ranges — the richest table for modeling" },
];

const quirks = [
  { title: "Realistic distributions", desc: "Age follows real-world lab demographics. Result values are drawn from per-test distributions with clinically plausible reference ranges. Volume follows intraday and weekday curves observed in production systems." },
  { title: "Deliberate data-quality injection", desc: "Null join keys, zero-value insurance-style records, ~66% timestamp coverage, metadata header rows, batch-locked timestamps — the generator reproduces the exact messiness that breaks naive analyses in production." },
  { title: "Client personalities", desc: "Each of the five synthetic organizations gets a distinct profile: different scale, service mix, currency conventions, and quirks — so cross-client work faces real heterogeneity." },
  { title: "Known ground truth", desc: "Because anomalies and patterns are injected deliberately, detection performance is directly measurable — an evaluation advantage no real dataset offers." },
];

const standards = [
  { title: "Honest metrics only", desc: "Every reported metric comes from real model evaluation on held-out data. Where a model underperforms, the page says so." },
  { title: "No data leakage", desc: "Features that would not be available at prediction time are excluded. Reference ranges are used only to create labels — never as model inputs." },
  { title: "Stated limitations", desc: "Each project ends with an honest account of what the analysis cannot do and what a production deployment would require." },
  { title: "Validation discipline", desc: "Stratified splits, cross-validation, vocabulary-held-out probes, and appropriate metrics for imbalanced problems rather than accuracy alone." },
];

export default function MethodologyPage() {
  return (
    <div>
      <div className="bg-[#0F172A] relative">
        <div className="absolute top-0 left-0 right-0 h-[3px] bg-[#D97706]" />
        <div className="max-w-[1200px] mx-auto px-[32px] md:px-[48px] lg:px-[64px] pt-20 pb-20">
          <p className="font-mono text-[11px] font-semibold tracking-[0.12em] text-[#94A3B8] uppercase mb-4">
            The Synthetic Data
          </p>
          <h1 className="text-[2.5rem] md:text-[3rem] font-extrabold text-white leading-[1.1] tracking-[-0.02em] mb-5">
            Data engineered to behave like production.
          </h1>
          <p className="text-[1.0625rem] text-[#94A3B8] max-w-[600px] leading-[1.7]">
            Every record on this site is synthetic — generated by a custom
            Python pipeline that reproduces the structure, distributions, and
            data-quality quirks of real healthcare lab operations.
          </p>
        </div>
      </div>

      <div className="max-w-[820px] mx-auto px-[32px] md:px-[48px] lg:px-[64px] py-16 space-y-20">

        <section>
          <SectionLabel number="01" label="Why Synthetic" />
          <h2 className="text-[1.75rem] font-extrabold text-[#134E4A] leading-tight mb-4">
            The problem with real healthcare data in public.
          </h2>
          <p className="text-[1.0625rem] text-[#475569] leading-relaxed mb-4">
            Healthcare data is among the most privacy-sensitive data that exists.
            Even anonymized production data carries re-identification risk and
            contractual restrictions. For a public portfolio, the responsible
            answer is not to anonymize harder — it is to not use real data at all.
          </p>
          <p className="text-[1.0625rem] text-[#475569] leading-relaxed">
            The challenge then becomes making synthetic data hard enough to be
            worth analyzing. Toy datasets teach toy lessons. The generator behind
            this site is designed so that every project faces the same obstacles
            a production analysis would: broken joins, partial coverage, mixed
            languages, and dirty timestamps.
          </p>
        </section>

        <section>
          <SectionLabel number="02" label="The Schema" />
          <h2 className="text-[1.75rem] font-extrabold text-[#134E4A] leading-tight mb-4">
            Five organizations, one shared five-table model.
          </h2>
          <p className="text-[1.0625rem] text-[#475569] leading-relaxed mb-8">
            The relational schema mirrors how multi-tenant healthcare platforms
            actually structure lab operations data. Five synthetic client
            organizations share it, each with a distinct operational personality.
          </p>
          <div className="space-y-3">
            {tables.map(function renderTable(t, i) {
              const last = i === 4;
              const cls = "p-5 rounded-xl border " + (last ? "border-[#99F6E4] bg-[#F0FDFA]/60" : "border-[#E2E8F0] bg-white");
              return (
                <div key={t.name} className={cls}>
                  <code className={"font-mono text-sm font-bold " + (last ? "text-[#0D9488]" : "text-[#134E4A]")}>{t.name}</code>
                  <p className="text-[0.875rem] text-[#475569] mt-1.5">{t.desc}</p>
                </div>
              );
            })}
          </div>
        </section>

        <section>
          <SectionLabel number="03" label="Generation Principles" />
          <h2 className="text-[1.75rem] font-extrabold text-[#134E4A] leading-tight mb-6">
            What makes it behave like the real thing.
          </h2>
          <div className="space-y-4">
            {quirks.map(function renderQuirk(s, i) {
              return (
                <div key={i} className="flex gap-4 p-5 rounded-xl bg-white border border-[#E2E8F0]">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#F0FDFA] flex items-center justify-center">
                    <span className="w-2 h-2 rounded-full bg-[#0D9488]" />
                  </span>
                  <div>
                    <p className="font-semibold text-[#0F172A] text-[0.9375rem] mb-1">{s.title}</p>
                    <p className="text-[0.875rem] text-[#475569] leading-relaxed">{s.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        <section>
          <SectionLabel number="04" label="Analytical Standards" />
          <h2 className="text-[1.75rem] font-extrabold text-[#134E4A] leading-tight mb-6">
            The rules every project follows.
          </h2>
          <div className="space-y-4">
            {standards.map(function renderStandard(s, i) {
              return (
                <div key={i} className="flex gap-4 p-5 rounded-xl bg-white border border-[#E2E8F0]">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#F0FDFA] flex items-center justify-center">
                    <span className="w-2 h-2 rounded-full bg-[#0D9488]" />
                  </span>
                  <div>
                    <p className="font-semibold text-[#0F172A] text-[0.9375rem] mb-1">{s.title}</p>
                    <p className="text-[0.875rem] text-[#475569] leading-relaxed">{s.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

      </div>
    </div>
  );
}
