"use client";

import { motion } from "framer-motion";
import { FlaskConical, Database, BrainCircuit, BarChart3 } from "lucide-react";
import { fadeUp, staggerContainer, viewportConfig } from "@/lib/animations";

const pillars = [
  {
    icon: Database,
    title: "Modeled on Real Operations",
    description:
      "The schema, distributions, and data-quality quirks mirror production healthcare systems I work with professionally — five relational tables covering patients, orders, services, and lab results.",
  },
  {
    icon: FlaskConical,
    title: "Fully Synthetic by Design",
    description:
      "Every record is generated by a custom Python pipeline. No real patient, physician, facility, or transaction appears anywhere — which is exactly why the full dataset can be public.",
  },
  {
    icon: BrainCircuit,
    title: "End-to-End ML",
    description:
      "Each project covers the full lifecycle: problem framing, feature engineering, model training, validation, and business interpretation — not just notebooks.",
  },
  {
    icon: BarChart3,
    title: "Business-First Framing",
    description:
      "Every model is anchored to an operational problem — SLA breaches, turnaround delays, revenue anomalies. Accuracy metrics alone don't tell the story.",
  },
];

export function WhyShowcase() {
  return (
    <section className="bg-white py-24">
      <div className="max-w-[1200px] mx-auto px-[32px] md:px-[48px] lg:px-[64px]">
        <motion.div variants={staggerContainer} initial="hidden" whileInView="visible" viewport={viewportConfig}>
          <motion.div variants={fadeUp} className="mb-16 max-w-[640px]">
            <p className="font-mono text-[11px] font-semibold tracking-[0.12em] text-[#94A3B8] uppercase mb-4">
              Why Synthetic
            </p>
            <h2 className="text-[2rem] md:text-[2.5rem] font-extrabold text-[#134E4A] leading-tight tracking-tight mb-5">
              Healthcare data is uniquely rich.
              <br />
              And uniquely private.
            </h2>
            <p className="text-[1.0625rem] text-[#475569] leading-relaxed">
              I lead data operations at a healthcare SaaS company, where I built an
              internal training platform on this exact structure. This public
              version runs on synthetic data I engineered to preserve the
              analytical challenge — without exposing a single real record.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {pillars.map((pillar) => {
              const Icon = pillar.icon;
              return (
                <motion.div
                  key={pillar.title}
                  variants={fadeUp}
                  className="group p-8 rounded-xl border border-[#E2E8F0] hover:border-[#99F6E4] hover:shadow-[0_4px_24px_rgba(13,148,136,0.08)] transition-all duration-200 bg-white"
                >
                  <div className="flex items-start gap-5">
                    <div className="flex-shrink-0 w-11 h-11 rounded-lg bg-[#F0FDFA] flex items-center justify-center group-hover:bg-[#0D9488] transition-colors duration-200">
                      <Icon size={20} className="text-[#0D9488] group-hover:text-white transition-colors duration-200" />
                    </div>
                    <div>
                      <h3 className="text-[1rem] font-semibold text-[#0F172A] mb-2">
                        {pillar.title}
                      </h3>
                      <p className="text-[0.9375rem] text-[#475569] leading-relaxed">
                        {pillar.description}
                      </p>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
